### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroyItem' of undefined

### ISSUE THREAD

**Issue by stoked74** [Evmorov/tab-close-double-click#1]
[Enter steps to reproduce below:]
1. Double click on an open tab
2. ...

**Atom Version**: 1.3.3
**System**: Mac OS X 10.11.2
**Thrown From**: [tab-close-double-click](https://github.com/Evmorov/tab-close-double-click) package, v2.0.1
### Stack Trace

Uncaught TypeError: Cannot read property 'destroyItem' of undefined

```
At /Users/Sam/.atom/packages/tab-close-double-click/lib/tab-close-double-click.coffee:11

TypeError: Cannot read property 'destroyItem' of undefined
    at tabs-tab.<anonymous> (/Users/Sam/.atom/packages/tab-close-double-click/lib/tab-close-double-click.coffee:11:3)
    at atom-pane-container.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at atom-pane-container.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -1:40.8.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  8x -1:20 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:17.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "ignoredNames": [
      ".DS_Store"
    ],
    "themes": [
      "nucleus-dark-ui",
      "one-sharp-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.3
auto-indent, v0.5.0
emmet, v2.3.17
file-icon-supplement, v0.8.3
file-icons, v1.6.13
fold-functions, v0.4.3
foldername-tabs, v0.1.6
jshint, v1.8.3
meteor-api, v2.20.0
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-find-and-replace, v4.4.0
nucleus-dark-ui, v0.7.3
one-sharp-syntax, v1.1.1
open-recent, v4.0.1
save-session, vundefined
symbols-tree-view, v0.11.0
tab-close-double-click, v2.0.1

# Dev
No dev packages
```

**Comment by evmorov** [comment]
Can you please confirm that the problem exists after restarting the Atom editor?

**Comment by evmorov** [comment]
At another PC I've reproduced this bug (I updated the package). To fix it you just need to restart the editor. Sorry for inconvenience.
