### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroyItem' of undefined

### ISSUE THREAD

**Issue by pedro93** [Evmorov/tab-close-double-click#2]
This error appeared after removing a project folder from the Atom tree view, I noticed a file was still showing in the editor pane, when attempting to close the file tab this error showed.

**Atom Version**: 1.4.0
**System**: Mac OS X 10.10.5
**Thrown From**: [tab-close-double-click](https://github.com/Evmorov/tab-close-double-click) package, v2.0.1
### Stack Trace

Uncaught TypeError: Cannot read property 'destroyItem' of undefined

```
At /Users/pedrosilva/.atom/packages/tab-close-double-click/lib/tab-close-double-click.coffee:54

TypeError: Cannot read property 'destroyItem' of undefined
    at tabs-tab.<anonymous> (/Users/pedrosilva/.atom/packages/tab-close-double-click/lib/tab-close-double-click.coffee:54:18)
    at atom-pane-container.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at atom-pane-container.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -0:23.1.0 tabs:close-all-tabs (div.title.temp)
     -0:17 tree-view:remove-project-folder (div.header.list-item)
     -0:15.2.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "sublime-default-syntax"
    ],
    "disabledPackages": [
      "double-click-tree-view",
      "metrics",
      "project-manager"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "tree-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-pair, v2.0.10
auto-indent, v0.5.0
autohide-tree-view, v0.25.1
build, v0.52.0
emmet, v2.3.17
language-latex, v0.6.1
latex, v0.28.2
linter, v1.11.3
pdf-view, v0.39.0
sublime-default-syntax, v0.2.7
sync-settings, v0.6.0
tab-close-double-click, v2.0.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by evmorov** [comment]
Strange. Can't localize the problem. I've made a new version that will not give you this exception. I'll try to catch the problem. Let me know if you'll have problems again.

**Comment by pedro93** [comment]
I have updated to the newest package version 2.0.2, I will reopen the issue if the problem persists
